/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user information
         * @description Returns information about the currently authenticated user, including their authentication status, invitation status, admin status, and profile details.
         */
        get: operations["GetCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate GitHub OAuth login
         * @description Redirects the user to GitHub for OAuth authentication. Accepts an optional relative returnUrl to redirect back to after login.
         */
        get: operations["Login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out the current user
         * @description Clears the authentication cookie and signs out the authenticated user.
         */
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/smoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify authenticated access
         * @description Returns the authenticated user's ID. Requires the InvitedUser authorization policy.
         */
        get: operations["SmokeTest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{interviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an interview session
         * @description Returns the interview session with the given ID belonging to the authenticated user.
         */
        get: operations["GetInterview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List interview sessions
         * @description Returns interview sessions belonging to the authenticated user, optionally filtered by status.
         */
        get: operations["GetInterviews"];
        put?: never;
        /**
         * Create an interview session
         * @description Creates a new interview session in the Created state for the authenticated user.
         */
        post: operations["CreateInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{interviewId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an interview session
         * @description Transitions the session to Active and generates the first question.
         */
        post: operations["StartInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{interviewId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit an answer
         * @description Records the answer for the current turn and returns the next question if the session is still active.
         */
        post: operations["SubmitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{interviewId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete an interview session
         * @description Transitions an active interview session to the Completed state.
         */
        post: operations["CompleteInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{interviewId}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an interview session with turns and summary
         * @description Returns the interview session details with the given ID belonging to the authenticated user.
         */
        get: operations["GetInterviewDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{interviewId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a summary for an interview session
         * @description Generates a summary for a completed interview session.
         */
        post: operations["GenerateSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateInterviewRequest: {
            targetRole: string;
            focusArea: string;
            interviewType: components["schemas"]["InterviewTypeContract"];
            seniorityLevel: components["schemas"]["SeniorityLevelContract"];
            /** Format: int32 */
            questionCount: number;
        };
        CreateInterviewResponse: {
            /** Format: uuid */
            id: string;
            userId: string;
            status: components["schemas"]["InterviewStatusContract"];
            targetRole: string;
            focusArea: string;
            interviewType: components["schemas"]["InterviewTypeContract"];
            seniorityLevel: components["schemas"]["SeniorityLevelContract"];
            /** Format: int32 */
            questionCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        CurrentUserResponse: {
            isAuthenticated: boolean;
            isInvited: boolean;
            isAdmin: boolean;
            userId: null | string;
            identityProvider: null | string;
            displayName: null | string;
            githubLogin: null | string;
            avatarUrl: null | string;
        };
        GetInterviewDetailsResponse: {
            /** Format: uuid */
            id: string;
            userId: string;
            status: components["schemas"]["InterviewStatusContract"];
            targetRole: string;
            focusArea: string;
            interviewType: components["schemas"]["InterviewTypeContract"];
            seniorityLevel: components["schemas"]["SeniorityLevelContract"];
            /** Format: int32 */
            questionCount: number;
            /** Format: int32 */
            answeredCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: int32 */
            totalScore: null | number;
            summary: null | components["schemas"]["GetInterviewDetailsResponseSummary"];
            turns: components["schemas"]["GetInterviewDetailsResponseTurn"][];
        };
        GetInterviewDetailsResponseAnswer: {
            text: string;
            /** Format: date-time */
            createdAt: string;
        };
        GetInterviewDetailsResponseEvaluation: {
            /** Format: int32 */
            overallScore: number;
            overallFeedback: string;
            dimensions: components["schemas"]["GetInterviewDetailsResponseEvaluationDimension"][];
        };
        GetInterviewDetailsResponseEvaluationDimension: {
            key: string;
            label: string;
            /** Format: int32 */
            score: number;
            feedback: string;
        };
        GetInterviewDetailsResponseQuestion: {
            text: string;
            topic: string;
        };
        GetInterviewDetailsResponseSummary: {
            text: string;
            /** Format: date-time */
            createdAt: string;
        };
        GetInterviewDetailsResponseTurn: {
            /** Format: int32 */
            turnNumber: number;
            question: components["schemas"]["GetInterviewDetailsResponseQuestion"];
            answer: null | components["schemas"]["GetInterviewDetailsResponseAnswer"];
            evaluation: null | components["schemas"]["GetInterviewDetailsResponseEvaluation"];
            /** Format: date-time */
            createdAt: string;
        };
        GetInterviewsResponse: {
            /** Format: uuid */
            id: string;
            userId: string;
            status: components["schemas"]["InterviewStatusContract"];
            targetRole: string;
            focusArea: string;
            interviewType: components["schemas"]["InterviewTypeContract"];
            seniorityLevel: components["schemas"]["SeniorityLevelContract"];
            /** Format: int32 */
            questionCount: number;
            /** Format: int32 */
            answeredCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: int32 */
            totalScore: null | number;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        InterviewResponse: {
            /** Format: uuid */
            id: string;
            userId: string;
            status: components["schemas"]["InterviewStatusContract"];
            targetRole: string;
            focusArea: string;
            interviewType: components["schemas"]["InterviewTypeContract"];
            seniorityLevel: components["schemas"]["SeniorityLevelContract"];
            /** Format: int32 */
            questionCount: number;
            /** Format: int32 */
            answeredCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: int32 */
            totalScore: null | number;
            currentQuestion: null | components["schemas"]["QuestionContract"];
        };
        /** @enum {unknown} */
        InterviewStatusContract: "Created" | "Active" | "Completed";
        /** @enum {unknown} */
        InterviewTypeContract: "Technical" | "Behavioral" | "SystemDesign";
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        QuestionContract: {
            text: string;
            topic: string;
            /** Format: int32 */
            turnNumber: number;
        };
        /** @enum {unknown} */
        SeniorityLevelContract: "Junior" | "Middle" | "Senior";
        SmokeTestEndpointResponse: {
            status: string;
            userId: null | string;
        };
        StartInterviewResponse: {
            /** Format: uuid */
            id: string;
            userId: string;
            status: components["schemas"]["InterviewStatusContract"];
            targetRole: string;
            focusArea: string;
            interviewType: components["schemas"]["InterviewTypeContract"];
            seniorityLevel: components["schemas"]["SeniorityLevelContract"];
            /** Format: int32 */
            questionCount: number;
            /** Format: int32 */
            answeredCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
            currentQuestion: components["schemas"]["QuestionContract"];
        };
        SubmitAnswerRequest: {
            /** Format: int32 */
            turnNumber: number;
            answer: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: {
                returnUrl?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SmokeTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmokeTestEndpointResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetInterviews: {
        parameters: {
            query?: {
                status?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInterviewsResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateInterview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInterviewRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInterviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    StartInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartInterviewResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SubmitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interviewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CompleteInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetInterviewDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInterviewDetailsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GenerateSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
