/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate GitHub OAuth login
         * @description Redirects the user to GitHub for OAuth authentication. Accepts an optional relative returnUrl to redirect back to after login.
         */
        get: operations["Login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out the current user
         * @description Clears the authentication cookie and signs out the authenticated user.
         */
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/smoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify authenticated access
         * @description Returns the authenticated user's ID. Requires the InvitedUser authorization policy.
         */
        get: operations["SmokeTest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{interviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an interview session
         * @description Returns the interview session with the given ID belonging to the authenticated user.
         */
        get: operations["GetInterview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List interview sessions
         * @description Returns interview sessions belonging to the authenticated user, optionally filtered by status.
         */
        get: operations["GetInterviews"];
        put?: never;
        /**
         * Create an interview session
         * @description Creates a new interview session in the Created state for the authenticated user.
         */
        post: operations["CreateInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{interviewId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an interview session
         * @description Transitions the session to Active and generates the first question.
         */
        post: operations["StartInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{sessionId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit an answer
         * @description Records the answer for the current turn and returns the next question if the session is still active.
         */
        post: operations["SubmitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{interviewId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete an interview session
         * @description Transitions an active interview session to the Completed state.
         */
        post: operations["CompleteInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateInterviewRequest: {
            targetRole: components["schemas"]["String"];
            focusArea: components["schemas"]["String"];
            interviewType: components["schemas"]["String"];
            seniorityLevel: components["schemas"]["String"];
            questionCount: components["schemas"]["Int32"];
        };
        CreateInterviewResponse: {
            id: components["schemas"]["Guid"];
            userId: components["schemas"]["String"];
            status: components["schemas"]["String"];
            targetRole: components["schemas"]["String"];
            focusArea: components["schemas"]["String"];
            interviewType: components["schemas"]["String"];
            seniorityLevel: components["schemas"]["String"];
            questionCount: components["schemas"]["Int32"];
            createdAt: components["schemas"]["DateTimeOffset"];
        };
        /** Format: date-time */
        DateTimeOffset: string;
        GetInterviewFeedback: {
            score: components["schemas"]["Int32"];
            summary: null | components["schemas"]["String"];
        };
        GetInterviewQuestion: {
            text: components["schemas"]["String"];
            topic: components["schemas"]["String"];
        };
        GetInterviewResponse: {
            id: components["schemas"]["Guid"];
            userId: components["schemas"]["String"];
            status: components["schemas"]["String"];
            targetRole: components["schemas"]["String"];
            focusArea: components["schemas"]["String"];
            interviewType: components["schemas"]["String"];
            seniorityLevel: components["schemas"]["String"];
            questionCount: components["schemas"]["Int32"];
            answeredCount: components["schemas"]["Int32"];
            createdAt: components["schemas"]["DateTimeOffset"];
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
            feedback: null | components["schemas"]["GetInterviewFeedback"];
            currentQuestion: null | components["schemas"]["GetInterviewQuestion"];
        };
        GetInterviewsResponse: {
            id: components["schemas"]["Guid"];
            userId: components["schemas"]["String"];
            status: components["schemas"]["String"];
            targetRole: components["schemas"]["String"];
            focusArea: components["schemas"]["String"];
            interviewType: components["schemas"]["String"];
            seniorityLevel: components["schemas"]["String"];
            questionCount: components["schemas"]["Int32"];
            answeredCount: components["schemas"]["Int32"];
            createdAt: components["schemas"]["DateTimeOffset"];
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: int32 */
            totalScore: null | number | string;
        };
        /** Format: uuid */
        Guid: string;
        HttpValidationProblemDetails: {
            type?: null | components["schemas"]["String"];
            title?: null | components["schemas"]["String"];
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | components["schemas"]["String"];
            instance?: null | components["schemas"]["String"];
            errors?: {
                [key: string]: components["schemas"]["String[]"];
            };
        };
        /** Format: int32 */
        Int32: number | string;
        ProblemDetails: {
            type?: null | components["schemas"]["String"];
            title?: null | components["schemas"]["String"];
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | components["schemas"]["String"];
            instance?: null | components["schemas"]["String"];
        };
        SmokeTestEndpointResponse: {
            status: components["schemas"]["String"];
            userId: null | components["schemas"]["String"];
        };
        StartInterviewQuestion: {
            text: components["schemas"]["String"];
            topic: components["schemas"]["String"];
        };
        StartInterviewResponse: {
            id: components["schemas"]["Guid"];
            userId: components["schemas"]["String"];
            status: components["schemas"]["String"];
            targetRole: components["schemas"]["String"];
            focusArea: components["schemas"]["String"];
            interviewType: components["schemas"]["String"];
            seniorityLevel: components["schemas"]["String"];
            questionCount: components["schemas"]["Int32"];
            answeredCount: components["schemas"]["Int32"];
            createdAt: components["schemas"]["DateTimeOffset"];
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
            currentQuestion: components["schemas"]["StartInterviewQuestion"];
        };
        String: string;
        "String[]": components["schemas"]["String"][];
        SubmitAnswerFeedback: {
            score: components["schemas"]["Int32"];
            summary: null | components["schemas"]["String"];
        };
        SubmitAnswerQuestion: {
            text: components["schemas"]["String"];
            topic: components["schemas"]["String"];
        };
        SubmitAnswerRequest: {
            turnNumber: components["schemas"]["Int32"];
            answer: components["schemas"]["String"];
        };
        SubmitAnswerResponse: {
            id: components["schemas"]["Guid"];
            userId: components["schemas"]["String"];
            status: components["schemas"]["String"];
            targetRole: components["schemas"]["String"];
            focusArea: components["schemas"]["String"];
            interviewType: components["schemas"]["String"];
            seniorityLevel: components["schemas"]["String"];
            questionCount: components["schemas"]["Int32"];
            answeredCount: components["schemas"]["Int32"];
            createdAt: components["schemas"]["DateTimeOffset"];
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
            feedback: null | components["schemas"]["SubmitAnswerFeedback"];
            currentQuestion: null | components["schemas"]["SubmitAnswerQuestion"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Login: {
        parameters: {
            query?: {
                returnUrl?: components["schemas"]["String"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SmokeTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmokeTestEndpointResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interviewId: components["schemas"]["Guid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInterviewResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetInterviews: {
        parameters: {
            query?: {
                status?: components["schemas"]["String[]"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInterviewsResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateInterview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInterviewRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInterviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    StartInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interviewId: components["schemas"]["Guid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartInterviewResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SubmitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["schemas"]["Guid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitAnswerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CompleteInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interviewId: components["schemas"]["Guid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
